### ISSUE TITLE
file not found error on import

### ISSUE THREAD

**Issue by npomfret** [CreativeSDK/ios-getting-started-samples#25]
I've followed the [Configuring Xcode For Using Dynamic AdobeCreativeSDK Frameworks](https://github.com/CreativeSDK/ios-getting-started-samples/blob/master/Getting%20Started/Guide/GettingStarted.md#configuring-xcode-for-using-dynamic-adobecreativesdk-frameworks) to the letter in Xcode 8.2 but I'm getting a _File not Found_ error at `#import <AdobeCreativeSDKCore/AdobeCreativeSDKCore.h>`

I've tried all sorts of combinations of getting the framework into my Xcode project but I simply can't get Xcode to find the header file.  Any ideas?  Are these instructions definitely correct?

**Comment by milan-mgu** [comment]
@npomfret Have you find the solution for this? I am facing the same issue.
